### ISSUE TITLE
[low priority] NullReferenceException while loading the game

### ISSUE THREAD

**Issue by mongoose11235813** [Xarun/CraftHistory#1]
##### ksp 1.0.4

I noticed this while trying to figure out why RealChute doesn't work properly with Smart Parts.
###### mods required:

CraftHistory
KerboKatzUtilities
###### steps:
1. load the game (don't have to load/create any saves)
2. look into your output_log.txt

Exceptions are always a bad thing right?

**Comment by mongoose11235813** [comment]
##### Nailed it down even more:

##### Log: https://www.dropbox.com/s/e67dupncye44ic0/kerbokstzbugoutput_log.txt?dl=0

##### mods required:

KerboKatzUtilities
So it's not in the CraftHistory.
Should I close this issue and open one in the KerboKatzUtilities repository instead?

**Comment by mongoose11235813** [comment]
low priority because it doesn't seem to break anything important.

**Comment by Xarun** [comment]
This exception doesn't break anything and is already fixed on my local version. Once i get some time I'll update all the mods to include the change.

**Comment by Xarun** [comment]
Fixed with the new KerboKatzUtilities.
